# Generated by Django 5.2.8 on 2025-11-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carro', models.CharField(max_length=100)),
                ('imagem', models.TextField()),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
    ]
